## config, also see : https://github.com/mojombo/jekyll/wiki/Configuration
lsi:  true ## Produces an index for related posts.
pygments: true
#baseurl: http://www.zavakid.com/
#url: http://www.zavakid.com
name : 说者无意
description : 代码如诗，生活如画
assets_path : /themes/foundation
permalink : /:year/:month/:day/:title/
